-- Run as SYSTEM or another DBA user first:
-- CREATE USER employee_app IDENTIFIED BY employee_app;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO employee_app;
-- ALTER USER employee_app QUOTA UNLIMITED ON USERS;

-- Then connect as employee_app and run:
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID   NUMBER(19) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL         VARCHAR2(150 CHAR) NOT NULL UNIQUE,
    DEPARTMENT    VARCHAR2(80 CHAR) NOT NULL,
    SALARY        NUMBER(12,2) NOT NULL,
    JOIN_DATE     DATE NOT NULL,
    CONSTRAINT CHK_EMPLOYEE_SALARY CHECK (SALARY > 0)
);

CREATE SEQUENCE EMPLOYEE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
